### ISSUE TITLE
--trust-server-cert command line option not working

### ISSUE THREAD

**Issue by eajeaj** [bhank/ScriptDB#4]
The command line option **--trust-server-cert** is rejected by the latest release of scriptdb.exe with the following error:
   _Unknown parameter: --trust-server-cert_
I checked the latest source code and that parameter does not seem to be included in the latest source code.

Thanks for the great software!

**Comment by bhank** [comment]
Hello. The `--trust-server-cert` option is actually a parameter passed to [SvnCompleteSync](https://github.com/bhank/SVNCompleteSync) (the parameter is defined [here](https://github.com/bhank/SVNCompleteSync/blob/0a0e2041757c6a6590a14a70e77eacc1a791b145/SvnClient/Parameters.cs#L43)), not to ScriptDb itself.

From an example in the readme: `--postscriptingcommand="SvnClient.exe completesync --message=\"Updating {database} on {server}\" \"{path}\{databaseclean}\" --verbose --trust-server-cert"`

The `--postscriptingcommand` parameter is passed to ScriptDb, to tell it to run that SvnClient.exe command line (including `--trust-server-cert`) after each database is scripted.

**Comment by eajeaj** [comment]
Thanks!
